"""Pooled PostgreSQL transactions for isolated Phoney workspaces.

Only the existing stores' bound ``?`` parameters are adapted. SQL dialect
differences are explicit in the stores; this is not a general SQL translator.
Every store in a workspace takes the same database transaction lock, preserving
SQLite's serialized import, quota, publication and optimistic-edit guarantees
across threads and server processes.
"""

import atexit
from contextlib import contextmanager
import hashlib
import os
import re
import threading


SCHEMA_VERSION = 1
_POOLS = {}
_POOL_LOCK = threading.Lock()

TABLES = {
    "contacts": "id TEXT PRIMARY KEY, kind TEXT NOT NULL, phone TEXT NOT NULL UNIQUE, "
                "payload TEXT NOT NULL, insertion_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE",
    "agents": "id TEXT PRIMARY KEY, fingerprint TEXT NOT NULL UNIQUE, payload TEXT NOT NULL, "
              "insertion_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE",
    "call_notifications": "id TEXT PRIMARY KEY, payload TEXT NOT NULL, unread INTEGER NOT NULL",
    "notification_state": "id INTEGER PRIMARY KEY CHECK(id=1)",
    "voices": "id TEXT PRIMARY KEY, payload TEXT NOT NULL",
    "revisions": "agent_id TEXT NOT NULL, revision BIGINT NOT NULL, payload TEXT NOT NULL, "
                 "PRIMARY KEY(agent_id,revision)",
    "current_agents": "id TEXT PRIMARY KEY, revision BIGINT NOT NULL, "
                      "slot INTEGER UNIQUE CHECK(slot IS NULL OR slot BETWEEN 1 AND 9)",
    "grants": "digest TEXT PRIMARY KEY, expires DOUBLE PRECISION NOT NULL",
    "owner_sessions": "digest TEXT PRIMARY KEY, expires DOUBLE PRECISION NOT NULL",
    "clone_receipts": "key TEXT PRIMARY KEY, payload TEXT NOT NULL",
    "agent_setup": "key TEXT PRIMARY KEY, value TEXT NOT NULL",
}


class PostgresUnavailable(Exception):
    """Safe public error; connection strings and driver errors stay private."""


def schema_name(workspace_id):
    if not isinstance(workspace_id, str) or not workspace_id or len(workspace_id) > 200:
        raise ValueError("Enter a workspace identifier of at most 200 characters.")
    return "phoney_ws_" + hashlib.sha256(workspace_id.encode("utf-8")).hexdigest()[:32]


def _dependencies():
    try:
        import psycopg
        import psycopg_pool
        return psycopg, psycopg_pool
    except ImportError:
        raise PostgresUnavailable("PostgreSQL storage dependencies are unavailable.") from None


def _pool(database_url):
    if not isinstance(database_url, str) or not database_url:
        raise PostgresUnavailable("PostgreSQL storage is not configured.")
    _, pool_module = _dependencies()
    # Never reuse a background-thread pool inherited by a forked process.
    key = os.getpid(), database_url
    with _POOL_LOCK:
        pool = _POOLS.get(key)
        if pool is None or pool.closed:
            pool = pool_module.ConnectionPool(
                database_url, min_size=0, max_size=8, timeout=5, max_waiting=64,
                kwargs={"connect_timeout": 5, "application_name": "phoney", "client_encoding": "UTF8"},
                check=pool_module.ConnectionPool.check_connection,
                name="phoney-storage", open=True,
            )
            _POOLS[key] = pool
        return pool


def close_pools():
    """Release pooled connections on application shutdown or after tests."""
    with _POOL_LOCK:
        pools = list(_POOLS.values())
        _POOLS.clear()
    for pool in pools:
        pool.close()


atexit.register(close_pools)


class Connection:
    """The tiny SQLite-compatible execute surface used by Phoney stores."""

    is_postgres = True
    insertion_order = "insertion_order"

    def __init__(self, connection, *, row_factory=None):
        self.raw = connection
        self.row_factory = row_factory

    def execute(self, query, parameters=()):
        cursor = self.raw.cursor(row_factory=self.row_factory)
        cursor.execute(query.replace("?", "%s"), parameters)
        return cursor

    def executemany(self, query, parameters):
        cursor = self.raw.cursor(row_factory=self.row_factory)
        cursor.executemany(query.replace("?", "%s"), parameters)
        return cursor


def prepare_schema(connection):
    """Initialize/check a workspace under its advisory transaction lock."""
    connection.execute("CREATE TABLE IF NOT EXISTS phoney_storage_meta "
                       "(id INTEGER PRIMARY KEY CHECK(id=1), version INTEGER NOT NULL)")
    row = connection.execute("SELECT version FROM phoney_storage_meta WHERE id=1").fetchone()
    if row is not None and row[0] != SCHEMA_VERSION:
        raise PostgresUnavailable("PostgreSQL workspace storage version is unsupported.")
    for table, columns in TABLES.items():
        connection.execute(f"CREATE TABLE IF NOT EXISTS {table} ({columns})")
    connection.execute("INSERT INTO phoney_storage_meta VALUES (1,?) ON CONFLICT(id) DO NOTHING",
                       (SCHEMA_VERSION,))


def _ensure_workspace(raw, workspace_id, schema):
    """Keep workspace identity and phone routing metadata outside tenant schemas."""
    ready = raw.execute("SELECT to_regclass('phoney_catalog.workspaces'), "
                        "to_regclass('phoney_catalog.workspace_phone_numbers')").fetchone()
    if not all(ready):
        # Concurrent first starts in different workspaces must not race their
        # shared catalog DDL. Ordinary initialized workspaces avoid this lock.
        raw.execute("SELECT pg_advisory_xact_lock(%s)", (628678446734032435,))
        raw.execute("CREATE SCHEMA IF NOT EXISTS phoney_catalog")
        raw.execute("CREATE TABLE IF NOT EXISTS phoney_catalog.workspaces "
                    "(id TEXT PRIMARY KEY, schema_name TEXT NOT NULL UNIQUE)")
        raw.execute("CREATE TABLE IF NOT EXISTS phoney_catalog.workspace_phone_numbers "
                    "(phone_number TEXT PRIMARY KEY, workspace_id TEXT NOT NULL "
                    "REFERENCES phoney_catalog.workspaces(id))")
    raw.execute("INSERT INTO phoney_catalog.workspaces(id,schema_name) VALUES(%s,%s) "
                "ON CONFLICT(id) DO NOTHING", (workspace_id, schema))
    row = raw.execute("SELECT schema_name FROM phoney_catalog.workspaces WHERE id=%s", (workspace_id,)).fetchone()
    if row is None or row[0] != schema:
        raise PostgresUnavailable("Workspace schema metadata is inconsistent.")


def register_workspace(database_url, workspace_id="default", phone_number=""):
    """Register stable workspace identity and an optional E.164 phone number.

    This records future routing metadata; it does not introduce multi-workspace
    Twilio routing or scope the existing filesystem call archive.
    """
    if phone_number and not re.fullmatch(r"\+[1-9][0-9]{7,14}", phone_number):
        raise ValueError("Enter a phone number with a + country code.")
    with transaction(database_url, workspace_id) as connection:
        if phone_number:
            connection.execute("INSERT INTO phoney_catalog.workspace_phone_numbers "
                               "(phone_number,workspace_id) VALUES (?,?) ON CONFLICT(phone_number) DO NOTHING",
                               (phone_number, workspace_id))
            owner = connection.execute("SELECT workspace_id FROM phoney_catalog.workspace_phone_numbers "
                                       "WHERE phone_number=?", (phone_number,)).fetchone()
            if owner[0] != workspace_id:
                raise PostgresUnavailable("The phone number already belongs to another workspace.")
    return {"id": workspace_id, "schema": schema_name(workspace_id), "phone_number": phone_number}


@contextmanager
def transaction(database_url, workspace_id="default", *, row_factory=None, initialize=True, read_only=False,
                storage_tables=True):
    """Commit/rollback a pooled transaction, with a transaction-local schema.

    ``initialize=False`` is available for read-only migration inspection; no
    application schema/table is created in that mode.
    """
    psycopg, pool_module = _dependencies()
    schema = schema_name(workspace_id)
    if read_only and initialize:
        raise ValueError("Read-only transactions cannot initialize workspace storage.")
    lock = int.from_bytes(hashlib.sha256(schema.encode()).digest()[:8], "big", signed=True)
    try:
        with _pool(database_url).connection() as raw:
            if read_only:
                raw.execute("SET TRANSACTION READ ONLY")
            raw.execute("SET LOCAL lock_timeout = '5s'")
            raw.execute("SET LOCAL statement_timeout = '15s'")
            raw.execute("SELECT pg_advisory_xact_lock(%s)", (lock,))
            if initialize:
                if workspace_id != "__auth__":
                    _ensure_workspace(raw, workspace_id, schema)
                raw.execute(psycopg.sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(psycopg.sql.Identifier(schema)))
            # Excluding public also prevents another workspace's absent table
            # from accidentally resolving to an unrelated public table.
            raw.execute(psycopg.sql.SQL("SET LOCAL search_path TO {}, pg_catalog").format(psycopg.sql.Identifier(schema)))
            connection = Connection(raw)
            if initialize and storage_tables:
                prepare_schema(connection)
            yield Connection(raw, row_factory=row_factory)
    except (psycopg.Error, pool_module.PoolTimeout, pool_module.PoolClosed):
        raise PostgresUnavailable("PostgreSQL storage is unavailable. Changes were not saved.") from None
